# Generated by Django 4.1.5 on 2023-02-04 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('min_active', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимальное количество активных сотрудников')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальная длительность обеда')),
                ('employees', models.ManyToManyField(blank=True, related_name='group_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_managers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='breaks.organisation', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
    ]
