# Generated by Django 4.1.5 on 2023-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_replacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Стату смены',
                'verbose_name_plural': 'Статусы смены',
                'ordering': ('sort',),
            },
        ),
    ]
