# Generated by Django 4.1.5 on 2023-02-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0005_replacementemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус обеда',
                'verbose_name_plural': 'Статусы обедов',
            },
        ),
        migrations.AlterModelOptions(
            name='replacementstatus',
            options={'verbose_name': 'Статус смены', 'verbose_name_plural': 'Статусы смены'},
        ),
    ]
