# Generated by Django 4.1.5 on 2023-02-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0007_break'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ('-replacement__date', 'break_start'), 'verbose_name': 'Обеденный перерыв', 'verbose_name_plural': 'Обеденные перерывы'},
        ),
        migrations.RemoveField(
            model_name='break',
            name='duration',
        ),
    ]
